# Generated by Django 4.2.23 on 2025-08-13 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('identity', 'Identity Verification'), ('human', 'Human Verification'), ('phone', 'Phone Verification'), ('email', 'Email Verification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_verification_request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID'), ('other', 'Other')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='verification/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.verificationrequest')),
            ],
            options={
                'db_table': 'verification_identity_document',
            },
        ),
        migrations.CreateModel(
            name='HumanVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_type', models.CharField(choices=[('captcha', 'CAPTCHA'), ('puzzle', 'Puzzle'), ('question', 'Question'), ('image', 'Image Recognition')], max_length=20)),
                ('challenge_data', models.JSONField()),
                ('user_response', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_verifications', to='verification.verificationrequest')),
            ],
            options={
                'db_table': 'verification_human_verification',
            },
        ),
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_verification_session',
                'indexes': [models.Index(fields=['session_token'], name='verificatio_session_d84dd3_idx'), models.Index(fields=['expires_at'], name='verificatio_expires_2c5464_idx')],
            },
        ),
    ]
